### ISSUE TITLE
Display contact details of patient's family member

### ISSUE THREAD

**Issue by Ramanathan0908** [AY2223S1-CS2103T-T12-4/tp#11]
As a private nurse I want to know the patient's family member's details so I can contact them in case of emergency.

**Comment by rama-pang** [comment]
Perhaps we could use a `Person` for this; i.e. add a `List<Person> emergencyContacts;` field to `Patient`.

As an additional note, perhaps we could make having a `p/PHONE_NUMBER e/EMAIL a/ADDRESS` be optional?
