### ISSUE TITLE
add customised command syntax

### ISSUE THREAD

**Issue by izzahaj** [AY2223S1-CS2103T-T12-4/tp#133]
As a user I want to be able to add customised command syntax to tailor to my typing preferences so that I can manage my patients even faster.

**Comment by rama-pang** [comment]
I'm thinking of using a `Translator` for converting custom command keywords to the established ones. `Translator` will also be responsible for managing #147.

Might additionally need:
- A settings tab to customize commands
- User preference save file
- Duplicate commands check

**Comment by izzahaj** [comment]
> I'm thinking of using a `Translator` for converting custom command keywords to the established ones. `Translator` will also be responsible for managing #147.
> 
> Might additionally need:
> 
> * A settings tab to customize commands
> * User preference save file
> * Duplicate commands check

Perhaps we could use a `HashMap` to store customised commands as unique keys and map them to established commands (the values) so duplicate commands can be caught easily.
