### ISSUE TITLE
Update command syntax to accept index-based parameters

### ISSUE THREAD

**Issue by rama-pang** [AY2223S1-CS2103T-T12-4/tp#147]
E.g.:
- `edit -p PATIENT_INDEX -t TASK_INDEX` as a shorthand for `editTask`;
- `edit -p PATIENT_INDEX` or `edit PATIENT_INDEX` as shorthand for `editPatient`.

**Comment by izzahaj** [comment]
Does this mean there will be two commands that can be used to edit a task i.e. using `edit` or `editTask`?
