### ISSUE TITLE
Change occurrences of ArrayList to List in ConditionList

### ISSUE THREAD

**Issue by BlopApple** [AY2223S1-CS2103T-T12-4/tp#187]
Referring to #181 

Change `private ArrayList<Condition> internalConditionList` to `private final List<Condition> internalConditionList`
Change all occurrences of `ArrayList<Condition> ... = new ArrayList<>(...);` to `List<Condition> ... = new ArrayList<>(...);`
Make `getInternalList()` to return `List<Condition>` instead of `ArrayList<Condition>`

Would appreciate the above changes for both consistency and the reason that javafx gui elements usually operate using `List` interfaces.

**Comment by izzahaj** [comment]
@Ramanathan0908 @BlopApple Would this change apply to `TaskList` as well?

**Comment by BlopApple** [comment]
Yes ideally `TaskList` would have to change as well
