### ISSUE TITLE
Integrate undo and redo command into GUI

### ISSUE THREAD

**Issue by BlopApple** [AY2223S1-CS2103T-T12-4/tp#189]
GUI should reflect the status of `undo` and `redo` commands for specific commands such as `add`, `edit` and `delete` commands.

**Comment by rama-pang** [comment]
Perhaps in each snapshot of the `AddressBook`, we could additionally store the `Command` as well?

**Comment by BlopApple** [comment]
I think it would be sufficient to additionally store the `CommandResult` instead of `Command`.
