### ISSUE TITLE
Fix and update behavior of `updateFilteredPersonList` after every command

### ISSUE THREAD

**Issue by rama-pang** [AY2223S1-CS2103T-T12-4/tp#214]
In `ModelManager.java`, I believe `updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);` should be moved to the `AddPatientCommand` instead, as it is part of a command.

Also, in general, perhaps we could deprecate `model.updateFilteredPersonList(Model.PREDICATE_SHOW_ALL_PERSONS);`. Instead,
- If a patient is added, it is appended to the back of the currently displayed list.
- If a patient is edited, the currently displayed person list should be unchanged, except reflecting the changes to the person on the person card. To achieve this behavior, we can simply remove the `model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);` line on `EditPatientCommand`, `AddTaskCommand`, `EditTaskCommand`, and `DeleteTaskCommand`.
- If a patient is deleted, the currently displayed person list should remove that deleted person. The current implementation already has this behavior.

**Comment by BlopApple** [comment]
These behaviors are being resolved in the feature-ui branch. Will create PR once it is ready.
