### ISSUE TITLE
Display person details `commandType.Edit_Patient` even if duplicate or invalid attribute index is provided

### ISSUE THREAD

**Issue by izzahaj** [AY2223S1-CS2103T-T12-4/tp#251]
Currently, if you attempt to add a duplicate condition or a condition index that exceeds the size of the condition list, the output panel remains as the last displayed output panel. Perhaps we could display the intended patient's details in the output panel for these two invalid cases, so it's easier to see the condition list (and for other 'list' attributes as well).

I've messed around with the GUI a bit to get this behaviour by adding the `setPatientOfInterest()` line in the part of `AddConditionCommand#execute()` that handles duplicates (a similar modification was made in `DeleteConditionCommand`:
```java
 try {
    updatedConditionList = patientToEdit.getConditions().add(condition);
} catch (DuplicateConditionException exception) {
    // attempts to display patient details when duplicate condition is input
    model.setPatientOfInterest(patientToEdit);
    throw new CommandException(MESSAGE_DUPLICATE_CONDITION);
}
```

In `MainWindow`, the catch block of `executeCommand()` is modified to always handle commands of type `EDIT_PATIENT`:
```java
// some code
    if (commandResult.isEditPatient()) {
        outputPanel.handleEditPatient(logic.getPatientOfInterest());
    }

    if (commandResult.isDeletePatient()) {
        outputPanel.handleDeletePatient(logic.getPatientOfInterest());
    }

    return commandResult;
} catch (CommandException | ParseException e) {
    // handle any any changes to patient details
    outputPanel.handleEditPatient(logic.getPatientOfInterest());
    logger.info("Invalid command: " + commandText);
    resultDisplay.setFeedbackToUser(e.getMessage());
    throw e;
}
```

This change would not work for non-integer attribute indices, since they are handled in the parser and not the command itself. I am not well-versed in the GUI code so I do not know if this modification is buggy.

**Comment by BlopApple** [comment]
Ok I will look into this suggestion.
