### ISSUE TITLE
[PE-D][Tester C] Suggestion for Interval_Time_Period field

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T12-4/tp#317]
Steps to reproduce: 
add -p 7 d/talk | 12-10-23 1345 |  1.5 years

Expected:
Create such a task

Actual:
Does not allow interval time period with decimal point.

Suggestion: Can allow for intervals like 1.5 years.
![feature flaw for interval time period.png](https://raw.githubusercontent.com/guokweijie/ped/main/files/99ce9133-853d-4861-85ec-1973a29ce6f6.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: guokweijie/ped#1

**Comment by rama-pang** [comment]
Having support for a floating-point time interval seems would be a bad decision as it's very ambiguous. E.g., if the user inputs `1.1 years`, should we treat this as `13 months` (rounded-down by month), `14` months (rounded-up by month), `1 year + 36 days` (rounded-down by day), `1 year + 37 days` (rounded-up by day), leap-year cases.

If the user wants to specify `1.5` years, they could specify it as `18 months` instead without ambiguity.

**Comment by rama-pang** [comment]
This is a feature suggestion, so will close this issue.
