### ISSUE TITLE
GUI doesn't show task diff caused by `undo` and `redo` correctly

### ISSUE THREAD

**Issue by rama-pang** [AY2223S1-CS2103T-T12-4/tp#330]
Steps to reproduce:
- Add two tasks; e.g., `Task2` and `Task3`.
- Wait until the minute time changes since you added both tasks; e.g., wait at least two minutes.
- Do the steps as shown

https://user-images.githubusercontent.com/55415829/198792299-6d34b00c-15d5-4ae8-bed5-56475b99d595.mp4

**Comment by rama-pang** [comment]
Another case, by adding a recurring task and undo/redo-ing the command.

![image](https://user-images.githubusercontent.com/55415829/200159588-76f25467-8a1c-4386-8d31-49fe440f4488.png)

**Comment by BlopApple** [comment]
Ya the current implementation of `ListModificationPair` is too simple to handle recurring tasks. I will drop the gui functionality that shows undo/redo for tasks.
