### ISSUE TITLE
[PE-D][Tester C] Edit task for date time does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T12-4/tp#337]
Steps to reproduce:
edit -p 3 -d 2 d/|23-10-22 0800

Expected:
Date time of task 2 for Charlotte to change

Actual:
Command does not work, shows error message.

![functionality bug for edit task.png](https://raw.githubusercontent.com/guokweijie/ped/main/files/43f0ffcb-eb99-4e73-bd10-72edf5f54477.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: guokweijie/ped#3

**Comment by rama-pang** [comment]
I think having this not work is fine (i.e. not a bug); we can specify it in the UG. It's similar to how when editing tags in AB3, you need to rewrite every tag (and this is arguably still better, since you only need to rewrite the title)
