### ISSUE TITLE
Wrong error message when editing task 

### ISSUE THREAD

**Issue by shogun187** [AY2223S1-CS2103T-T12-4/tp#426]
![error](https://user-images.githubusercontent.com/53176307/200175269-1bf93dad-b9d5-417e-97c1-b23eebae383b.PNG)

When providing an empty task description for edit task, provided error message is "This task already exists for this patient", which is kind of inaccurate.

**Comment by izzahaj** [comment]
might be because the edit task classes have not been refactored yet
